name: Documentation
on: [push]

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
        persist-credentials: false
    - uses: nikeee/docfx-action@v1.0.0
      with:
        args: docs/docfx.json
    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: docs/_site 
        TARGET_FOLDER: docs